config:
  SPRING_PROFILES_ACTIVE: "k8s"

azure:
  sqlServerHostname: tstimpdbssqa001.database.windows.net

database:
  legacyBaseServiceDbUserAd: "SA-AZURE-IMP-SQL-SOAPR-TST@Defra.onmicrosoft.com"
  legacyManagedIdentityUser: "tst-imp-soaprequest-sql"
  migrations:
    enabled: false

externalSecret:
  enabled: true
  refreshInterval: 1h
  secrets:
    - secretKey: BASE_SERVICE_DB_PASSWORD
      remoteKey: soapRequestDatabasePassword
    - secretKey: NEW_BASE_SERVICE_DB_PASSWORD
      remoteKey: soapRequestDatabasePasswordNew
