#https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
server:
  port: ${SERVICE_PORT:5260}
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /admin
      path-mapping:
        health: health-check
info:
    app:
        name: soapRequest microservice
        version: ${API_VERSION}
spring:
  security:
    jwt:
      jwks: ${SECURITY_JWT_JWKS}
      iss: ${SECURITY_JWT_ISS}
      aud: ${SECURITY_JWT_AUD}
  datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};user=${DB_USER};password=${DB_PASSWORD};trustServerCertificate=${TRUST_SERVER_CERTIFICATE};hostNameInCertificate=*.database.windows.net;encrypt=true;
      dialect: com.microsoft.sqlserver.jdbc.SQLServerDriver
      continueOnError: true
      initialize: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2008Dialect
audit:
  create: true
  read: true
  update: false
  delete: true