service: soaprequest-service

container:
  replicas: 1


livenessProbe: {}


database:
  enabled: true
  databaseNames: [ "soaprequest-microservice" ]
  migrations:
    enabled: true

externalSecret:
  enabled: true
  refreshInterval: 1h
  secrets:
    - secretKey: BASE_SERVICE_DB_PASSWORD
      remoteKey: legacyDatabasePassword1
    - secretKey: NEW_BASE_SERVICE_DB_PASSWORD
      remoteKey: legacyDatabasePassword2
